spring:
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
  flyway:
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    locations: classpath:db/migration
    schemas: ${MYSQL_DATABASE}
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    host: rabbitmq
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8086/.well-known/jwks.json

server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${spring.application.name}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8761/eureka

interservice:
  services:
    user_service: "http://user-service"
    auth_service: "http://auth-service"

rabbitmq:
  exchange:
    team: "team.exchange"
    user: "user.exchange"
  queue:
    userDelete: "user.delete"
  routing:
    received:
      user:
        delete: "user.delete"

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always