spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  rabbitmq: # TODO: Improve For Security
    password: guest
    username: guest
    port: 5672
    host: rabbit

server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8761/eureka

rabbitmq:
  exchange: "user.exchange"
  queue:
    imageKey: "user.imageKey"
  routing:
    published:
      user:
        delete: "user.delete"
        create: "user.create"
    received:
      user:
        imageChanged: "user.profile.image.changed"